use super::lib::*;
use super::lib::ItemManager;

// All my function comments were generated in codeium
// ↓ generated by codeium ↓

/// The main app component. It manages the state of the to-do list and
/// provides callback functions for adding tasks and folders.
///
/// It uses the `ItemManager` component to manage the state of the to-do list.
/// The `ItemManager` component provides functions for adding, removing, and
/// sorting items in the list.
///
/// The app component also provides callback functions for adding tasks and
/// folders. These callback functions are passed to the `ItemManager` component
/// which then calls the callback functions when the user clicks on the
/// "add-task" or "add-folder" buttons.
///
/// The app component renders a text input field, two buttons, and a
/// container element for the tasks. The tasks are rendered as a list of
/// labels and checkboxes. The app component also renders a version number
/// at the bottom of the page.
#[function_component(App)]
pub fn app() -> Html {
    let items = use_state(|| ItemManager::new());
    let input_value = use_state(String::new);

    let on_input = {
        let input_value = input_value.clone();
        Callback::from(move |e: InputEvent| {
            if let Some(input) = e.target_dyn_into::<web_sys::HtmlInputElement>() {
                input_value.set(input.value());
            }
        })
    };

    let add_task = {
        let items = items.clone();
        let input_value = input_value.clone();

        move |_| {
            items.add_task(&input_value, &items);
            input_value.set("".to_string());
        }
    };

    let add_folder = {
        let items = items.clone();
        let input_value = input_value.clone();

        move |_| {
            items.add_folder(&input_value, &items);
            input_value.set("".to_string());
        }
    };

    use_effect_with((), {
        let items = items.clone();
        move |_| {
            ItemManager::initialize_with_defaults(&items);
        }
    });

    html! {
        <div>
            <Global css={global_style()}/>
            <div>
                <h2 class={classes!(title())}>{"Todo-list | rust.ver"}</h2>
            </div>

            <div>
                <input
                    id="task_input"
                    type="text"
                    placeholder="Enter a new task or new folder"
                    class={classes!(task_input())}
                    value={(*input_value).clone()}
                    oninput={on_input}
                />
                <button
                    onclick={add_task}
                    class={classes!(task_button())}>
                    {"add-task"}
                </button>
                <button
                    onclick={add_folder}
                    class={classes!(task_button())}>
                    {"add-folder"}
                </button>
            </div>

            <div id="task-list">
                // tasks will be appended here
            </div>

            <a>{"ver 0.2.1"}</a>
        </div>
    }
}
