use super::lib::*;
use super::lib::ItemManager;
use crate::modules::lib::notification_utils::show_reload_notification;

// All my function comments were generated in codeium
// ↓ generated by windsurf ↓

/// The main app component. It manages the state of the to-do list and
/// provides callback functions for adding tasks and folders.
///
/// It uses the `ItemManager` component to manage the state of the to-do list.
/// The `ItemManager` component provides functions for adding, removing, and
/// sorting items in the list.
///
/// The app component also provides callback functions for adding tasks and
/// folders. These callback functions are passed to the `ItemManager` component
/// which then calls the callback functions when the user clicks on the
/// "add-task" or "add-folder" buttons.
///
/// The app component renders a text input field, two buttons, and a
/// container element for the tasks. The tasks are rendered as a list of
/// labels and checkboxes. The app component also renders a version number
/// at the bottom of the page.
#[function_component(App)]
pub fn app() -> Html {
    let items = use_state(|| ItemManager::new());
    let input_value = use_state(String::new);
    let settings_open = use_state(|| false);
    let current_theme = use_state(|| {
        if let Some(window) = web_sys::window() {
            if let Ok(Some(storage)) = window.local_storage() {
                if let Ok(Some(theme)) = storage.get_item("theme") {
                    return theme;
                }
            }
        }
        "default".to_string()
    });

    let history = use_state(|| History::new());

    let on_input = {
        let input_value = input_value.clone();
        Callback::from(move |e: InputEvent| {
            if let Some(input) = e.target_dyn_into::<web_sys::HtmlInputElement>() {
                input_value.set(input.value());
            }
        })
    };

    let add_task = {
        let items = items.clone();
        let input_value = input_value.clone();
        let history = history.clone();

        move |_: MouseEvent| {
            items.add_task(&input_value, &items, &history, false);
            input_value.set("".to_string());
            history.set(history.clear_redo());
        }
    };

    let add_folder = {
        let items = items.clone();
        let input_value = input_value.clone();
        let history = history.clone();

        move |_: MouseEvent| {
            items.add_folder(&input_value, &items, &history, false);
            input_value.set("".to_string());
            history.set(history.clear_redo());
        }
    };

    let handle_keypress = {
        let items = items.clone();
        let input_value = input_value.clone();
        let history = history.clone();

        Callback::from(move |e: KeyboardEvent| {
            if e.key() == "Enter" && !input_value.is_empty() {
                e.prevent_default();
                
                if e.shift_key() {
                    // Shift+Enter: Add folder
                    items.add_folder(&input_value, &items, &history, false);
                    
                } else {
                    // Enter: Add task
                    items.add_task(&input_value, &items, &history, false);
                }
                input_value.set("".to_string());
                history.set(history.clear_redo());
            }
        })
    };

    let undo_action = {
        let history = history.clone();
        let items = items.clone();
        Callback::from(move |_| {
            history.set(history.undo(items.clone(), &history));
            log!("undo_action was called")
        })
    };

    let redo_action = {
        let history = history.clone();
        let items = items.clone();
        Callback::from(move |_| {
            history.set(history.redo(items.clone(), &history));
            log!("Redo button clicked (functionality removed)");
        })
    };

    let toggle_settings = {
        let settings_open = settings_open.clone();
        Callback::from(move |_| {
            settings_open.set(!*settings_open);
        })
    };

    let change_theme = {
        let current_theme = current_theme.clone();
        let settings_open = settings_open.clone();
        Callback::from(move |theme: String| {
            // Save theme to local storage
            if let Some(window) = web_sys::window() {
                if let Ok(Some(storage)) = window.local_storage() {
                    let _ = storage.set_item("theme", &theme);
                }
            }
            
            // Show reload notification
            show_reload_notification();
            
            // Update theme state
            current_theme.set(theme);
            
            // Close settings modal
            settings_open.set(false);
        })
    };

    let _debug_action = {
        let history = history.clone();
        // let items = items.clone();
        Callback::from(move |_: MouseEvent| {
            log!("Debug button clicked");
            log!(format!("History: {:?}", history));
            // log!(format!("Items: {:?}", items));
        })
    };

    use_effect_with((), {
        let items = items.clone();
        let history = history.clone();
        move |_| {
            ItemManager::initialize_with_defaults(&items, &history);
        }
    });

    html! {
        <>
            <Global css={global_style_for_theme(&current_theme.clone())}/>
            <div>
                <h2 class={classes!(title())}>{"Todo-list | rust.ver"}</h2>
            </div>

            <div class={classes!(input_container())}>
                <button
                    onclick={toggle_settings.clone()}
                    class={classes!(settings_button())}>
                    {"⚙️"}
                </button>
                // <button onclick={debug_action}>
                //     {"debug"}
                // </button>
                <div class={classes!(undo_redo_container())}>
                    <button
                        onclick={undo_action}
                        class={classes!(undo_redo_button())}>
                        {"↶ Undo"}
                    </button>
                    <button
                        onclick={redo_action}
                        class={classes!(undo_redo_button())}>
                        {"↷ Redo"}
                    </button>
                </div>
                <input
                    id="task_input"
                    type="text"
                    placeholder="Enter a new task or new folder"
                    class={classes!(task_input())}
                    value={(*input_value).clone()}
                    oninput={on_input}
                    onkeypress={handle_keypress}
                />
                <div class={classes!(action_buttons_container())}>
                    <button
                        onclick={add_task}
                        class={classes!(task_button())}>
                        {"add-task"}
                    </button>
                    <button
                        onclick={add_folder}
                        class={classes!(task_button())}>
                        {"add-folder"}
                    </button>
                </div>
            </div>

            <div id="task-list">
                // tasks will be appended here
            </div>

            {if *settings_open {
                html! {
                    <div class={classes!(settings_overlay())}>
                        <div class={classes!(settings_modal())}>
                            <div class={classes!(settings_header())}>
                                <h3>{"設定"}</h3>
                                <button onclick={toggle_settings.clone()} class={classes!(close_button())}>
                                    {"✕"}
                                </button>
                            </div>
                            <div class={classes!(settings_content())}>
                                <div class={classes!(settings_section())}>
                                    <h4>{"テーマ"}</h4>
                                    <div class={classes!(theme_options())}>
                                        <button 
                                            onclick={change_theme.reform(|_| "default".to_string())}
                                            class={classes!(theme_button())}>
                                            {"デフォルト"}
                                        </button>
                                        <button 
                                            onclick={change_theme.reform(|_| "dark".to_string())}
                                            class={classes!(theme_button())}>
                                            {"ダーク"}
                                        </button>
                                        <button 
                                            onclick={change_theme.reform(|_| "light".to_string())}
                                            class={classes!(theme_button())}>
                                            {"ライト"}
                                        </button>
                                    </div>
                                </div>
                                <div class={classes!(settings_section())}>
                                    <h4>{"リンク"}</h4>
                                    <a href="https://github.com/gurizoor/todolist-rs#" 
                                       target="_blank" 
                                       class={classes!(github_link())}>
                                        {"ソースコードやフィードバックはこちら"}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            } else {
                html! {}
            }}

            <a>{"ver 0.4.1"}</a>
        </>
    }
}
